### ISSUE TITLE
按照README里的文档来跑跑不起来

### ISSUE THREAD

**Issue by abell123456** [shendepu/moqui-react-ssr-demo#1]
您好，我按照README里的文档来跑跑不起来，在执行：`gradle build cleanAll load run`最后一步的时候，报以下异常：

`> Task :load  
Error: Unable to access jarfile moqui.war`  

麻烦能帮看下吗？

**Comment by shendepu** [comment]
命令应该是
gradle cleanAll build load run

发自我的 iPhone

在 2017年8月6日，09:18，xiangzhong.wxz <notifications@github.com<mailto:notifications@github.com>> 写道：


您好，我按照README里的文档来跑跑不起来，在执行：gradle build cleanAll load run最后一步的时候，报以下异常：

> Task :load Error: Unable to access jarfile moqui.war

麻烦能帮看下吗？
